// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.u64().primaryKey(),
  worldWidth: __t.f32().name("world_width"),
  worldHeight: __t.f32().name("world_height"),
  ballSpeed: __t.f32().name("ball_speed"),
  ballRadius: __t.f32().name("ball_radius"),
  ballLifetimeSeconds: __t.f32().name("ball_lifetime_seconds"),
});
