// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  playerId: __t.identity().primaryKey().name("player_id"),
  x: __t.f32(),
  y: __t.f32(),
  velocityX: __t.f32().name("velocity_x"),
  velocityY: __t.f32().name("velocity_y"),
  angle: __t.f32(),
  arcAngle: __t.f32().name("arc_angle"),
  innerRadius: __t.f32().name("inner_radius"),
  outerRadius: __t.f32().name("outer_radius"),
});
