// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export default __t.row({
  id: __t.identity().primaryKey(),
  x: __t.f32(),
  y: __t.f32(),
  name: __t.string(),
  aimAngle: __t.f32().name("aim_angle"),
  paddleArcAngle: __t.f32().name("paddle_arc_angle"),
  paddleRadius: __t.i32().name("paddle_radius"),
  playerRadius: __t.f32().name("player_radius"),
});
