// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Ball = __t.object("Ball", {
  id: __t.u64(),
  x: __t.f32(),
  y: __t.f32(),
  velocityX: __t.f32(),
  velocityY: __t.f32(),
  radius: __t.f32(),
  createdAt: __t.timestamp(),
  scheduledAt: __t.scheduleAt(),
});
export type Ball = __Infer<typeof Ball>;

export const Player = __t.object("Player", {
  id: __t.identity(),
  x: __t.f32(),
  y: __t.f32(),
  name: __t.string(),
  aimAngle: __t.f32(),
  paddleSize: __t.f32(),
});
export type Player = __Infer<typeof Player>;

