// THIS FILE IS AUTOMATICALLY GENERATED BY SPACETIMEDB. EDITS TO THIS FILE
// WILL NOT BE SAVED. MODIFY TABLES IN YOUR MODULE SOURCE CODE INSTEAD.

/* eslint-disable */
/* tslint:disable */
import {
  TypeBuilder as __TypeBuilder,
  t as __t,
  type AlgebraicTypeType as __AlgebraicTypeType,
  type Infer as __Infer,
} from "spacetimedb";

export const Ball = __t.object("Ball", {
  id: __t.u64(),
  x: __t.f32(),
  y: __t.f32(),
  velocityX: __t.f32(),
  velocityY: __t.f32(),
  radius: __t.f32(),
  createdAt: __t.timestamp(),
});
export type Ball = __Infer<typeof Ball>;

export const GameSettings = __t.object("GameSettings", {
  id: __t.u64(),
  worldWidth: __t.f32(),
  worldHeight: __t.f32(),
  ballSpeed: __t.f32(),
  ballRadius: __t.f32(),
  ballLifetimeSeconds: __t.f32(),
});
export type GameSettings = __Infer<typeof GameSettings>;

export const GameTick = __t.object("GameTick", {
  id: __t.u64(),
  scheduledAt: __t.scheduleAt(),
});
export type GameTick = __Infer<typeof GameTick>;

export const Player = __t.object("Player", {
  id: __t.identity(),
  x: __t.f32(),
  y: __t.f32(),
  name: __t.string(),
  aimAngle: __t.f32(),
  paddleArcAngle: __t.f32(),
  paddleRadius: __t.i32(),
  playerRadius: __t.f32(),
});
export type Player = __Infer<typeof Player>;

